"""Add requistion related tables

Revision ID: 05009b833f3b
Revises: 0a45251236d1
Create Date: 2025-05-07 12:10:25.111546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '05009b833f3b'
down_revision: Union[str, None] = '0a45251236d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'APPROVED', 'DELIVERED', name='requisitionstatus'), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('PIECE', 'PAIR', 'METER', 'GRAM', name='requisitionunit'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisition_items')
    op.drop_table('requisition')
    op.drop_table('items')
    # ### end Alembic commands ###
